### ISSUE TITLE
Interview mit Psychologiestudentin führen

### ISSUE THREAD

**Issue by ifrido** [supertoub/ch.bfh.bti7081.s2018.teamred#3]
@Interview mit Psychologiestudentin führen. Siehe [Interview.md](https://github.com/supertoub/ch.bfh.bti7081.s2018.teamred/blob/task1/INTERVIEW.md).

**Comment by riedoi** [comment]
23.03.2018 Interview geführt
24.03.2018 Interview erstellt:
