### ISSUE TITLE
System requirements

### ISSUE THREAD

**Issue by ifrido** [supertoub/ch.bfh.bti7081.s2018.teamred#45]
- Functional system requirements
- Non-functional system requirements 

Reffer to the this [slides](https://www.cpvrlab.ti.bfh.ch/bachelor/wm/BTI7081/soed/private/casestudy/CS2_Task2.pdf)

**Comment by riedoi** [comment]
resolved by 3e2974960882875150cc30bac1cd0ef606e287b8
