### ISSUE TITLE
System architecture

### ISSUE THREAD

**Issue by ifrido** [supertoub/ch.bfh.bti7081.s2018.teamred#46]
- Preface
- Introduction
- System architecture

Reffer to the this [slides](https://www.cpvrlab.ti.bfh.ch/bachelor/wm/BTI7081/soed/private/casestudy/CS2_Task2.pdf)

**Comment by riedoi** [comment]
Resolved by 3eb1ca7b7dc0b2189d657f3d1e5c6dde949fe7c8
