### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by ifrido** [supertoub/ch.bfh.bti7081.s2018.teamred#48]
- Testing
- Appendices

Reffer to the this [slides](https://www.cpvrlab.ti.bfh.ch/bachelor/wm/BTI7081/soed/private/casestudy/CS2_Task2.pdf)

**Comment by riedoi** [comment]
Resolved by 93194b768e78cb97bc69f800b5c8cc7e2ba3fd6e and 50d6b3a7a3674e9b95775183621b65eca1d59fb1
